		PROCESSOR 16F877
  		INCLUDE<P16F877.INC>

VAL EQU H'20'		; VARIABLES PARA EL DELAY

  		ORG 0H
  		GOTO INICIO
  
		ORG 05H
INICIO:	CLRF PORTA
       	CLRF PORTB
       	BSF STATUS,RP0    ;CAMBIA LA BANCO 1
       	BCF STATUS,RP1 
       	MOVLW 00H         ;CONFIGURA PUERTOS A Y E COMO ANALÓGICOS
       	MOVWF ADCON1
       	MOVLW 3FH         ;CONFIGURA EL PUERTO A COMO ENTRADA
       	MOVWF TRISA
       	MOVLW H'0'
       	MOVWF TRISB       ;CONFIGURA PUERTO B COMO SALIDA
       	BCF STATUS,RP0    ;REGRESA AL BANCO 0
       	MOVLW B'11000001' ;CONFIGURACIÓN ADCON0
       	MOVWF ADCON0      ;ADCS1=1 ADCS0=1 CHS2=0 CHS1=0 CHS0=0
	                      ;GO/DONE=0 - ADON=1

CICLO:  BSF ADCON0,2      ;CONVERSIÓN EN PROGRESO GO=1
       	CALL RETARDO      ;ESPERA QUE TERMINE LA CONVERSIÓN

ESPERA:	BTFSC ADCON0,2    ;PREGUNTA POR DONE(TERMINO CONVERSIÓN?)
       	GOTO ESPERA       ;NO, VUELVE A PREGUNTAR
       	MOVF ADRESH,0     ;MUEVE VE A W (VE=VOLTAJE DE ENTRADA)
       	SUBLW 130H        ;REALIZA 0CAH - W   (1/5VCC=0CCH)       
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR (CARRY=0?)
       	GOTO SALIDA0      ;SI, VE A SALIDA1 (VE < 1/3VCC)
       	MOVF ADRESH,0     ;NO, MUEVE VE A W
       	SUBLW 265H        ;194H - W          (2/3VCC=155H)
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR (CARRY=0)
       	GOTO SALIDA1      ;SI, SE CUMPLE QUE 1/3VCC<VE< 2/3VCC, NO, VERIFICA QUE W MENOR QUE VCC
       	MOVF ADRESH,0     ;MUEVE VE A W
       	SUBLW 398H      ;3FFH - W          (VCC=3FFH)
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR A VCC (CARRY=0?)
       	GOTO SALIDA2      ;SI, SE CUMPLE QUE 2/3VCC<VE<VCC
		MOVF ADRESH,0     ;MUEVE VE A W
       	SUBLW 3CAH      ;3FFH - W          (VCC=3FFH)
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR A VCC (CARRY=0?)
       	GOTO SALIDA3
		MOVF ADRESH,0     ;MUEVE VE A W
       	SUBLW H'3F7'      ;3FFH - W          (VCC=3FFH)
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR A VCC (CARRY=0?)
       	GOTO SALIDA4
		MOVF ADRESH,0     ;MUEVE VE A W
       	SUBLW H'3FF'      ;3FFH - W          (VCC=3FFH)
       	BTFSC STATUS,0    ;VERIFICA SI W ES MENOR A VCC (CARRY=0?)
       	GOTO SALIDA5

SALIDA0:	MOVLW H'0'
       		MOVWF PORTB   ;SALIDA 000
       		GOTO CICLO

SALIDA1:	MOVLW H'1'    ;SALIDA 001
       		MOVWF PORTB
       		GOTO CICLO

SALIDA2:	MOVLW H'2'    ;SALIDA 010
       		MOVWF PORTB
       		GOTO CICLO

SALIDA3:	MOVLW H'3'    ;SALIDA 011
       		MOVWF PORTB
       		GOTO CICLO
SALIDA4:	MOVLW H'4'    ;SALIDA 100
       		MOVWF PORTB
       		GOTO CICLO
SALIDA5:	MOVLW H'5'    ;SALIDA 101
       		MOVWF PORTB
       		GOTO CICLO

RETARDO:	MOVLW H'30'   ;DELAY DE 20 MICROSEG APROX.
 			MOVWF VAL

LOOP:	DECFSZ VAL
	    GOTO LOOP
      	RETURN
   		END
