        PROCESSOR 16F877        ;INDICA LA VERSIÓN DE PROCESADOR
        INCLUDE <P16F877.INC>   ;INCLUYE LA LIBRERÍA DE LA VERSIÓN DEL PROCESADOR

CONTA   EQU H'20'               ;VARIABLE PARA EL CONTEO DEL TIMER0
CONTA1  EQU H'21'               ;VARIABLE PARA EL CONTEO DEL TIMER0
DATO    EQU H'22'               ;VARIABLE PARA ALMACENAR LOS DATOS DEL PUERTO SERIE
DUTY    EQU H'23'               ;VARIBALE PARA ALMACENAR EL CICLO DE TRABAJO
VALOR1  EQU H'24'               ;VARIABLE PARA EL RETARDO
VALOR2  EQU H'25'               ;VARIABLE PARA EL RETARDO
VALOR3  EQU H'26'               ;VARIABLE PARA EL RETARDO
CTE1    EQU 80H                 ;CONSTANTE PARA EL RETARDO
CTE2    EQU 50H                 ;CONSTANTE PARA EL RETARDO
CTE3    EQU 60H                 ;CONSTANTE PARA EL RETARDO

        ORG 0                   ;CARGA AL VECTOR RESET LA DIRECCIÓN DE INICIO
        GOTO INICIO             

        ORG 4                   ;CARGA AL VECTOR DE INTERRUPCIONES
        GOTO INTERRUPCIONES

        ORG 5                   ;DIRECCIÓN DE INICIO DEL PROGRAMA DEL USUARIO
INICIO: CLRF PORTA              ;LIMPIA EL PUERTO A
        BSF STATUS, RP0         ;CAMBIO AL BANCO 1
        BCF STATUS, RP1         ;
        BCF TRISC, 1            ;CONFIGURA EL PIN C1 COMO SALIDA
        BCF TRISC, 2            ;CONFIGURA EL PIN C2 COMO SALIDA
        MOVLW D'255'            ;DEFINE EL PERIODO DEL CICLO DE TRABAJO
        MOVWF PR2               ;
        MOVLW 00H               ;SE CONFIGURA EL PUERTO A Y E COMO ANALÓGICOS
        MOVWF ADCON1            ;
        CLRF TRISB              ;CONFIGURA EL PUERTO B COMO SALIDA
        BSF TXSTA, BRGH         ;CONFIGURA BIT DE SELECCIÓN DE BAUDIOS BRGH = 1
        MOVLW D'129'            ;
        MOVWF SPBRG             ;ASIGNA LA TASA DE TRASMICIÓN A 9600 BAUDIOS
        BCF TXSTA, SYNC         ;CONFIGURA EL MODO DE COMUNICACIÓN EN ASINCRONO
        BSF TXSTA, TXEN         ;HABILITA LA TRASMICIÓN 
        MOVLW B'00000111'       ;CONFIGURACIÓN DE TEMPORIZADOR Y PREDIVISOR
        MOVWF OPTION_REG        ;
        BCF STATUS, RP0         ;REGRESO AL BANCO 0
        MOVLW B'00001100'       ;CONFIGURACIÓN DEL REGISTRO CCP2CON EN PWM
        MOVWF CCP2CON           ;
        MOVLW B'00000111'       ;CONFIGURACIÓN DEL POSTESCALADOR = 1, TIMER2 ACTIVADO, PREDIVISOR = 16
        MOVWF T2CON             ;
        MOVLW B'11000001'       ;CONFIGURACIÓN DE LA FRECUENCIA DE RELOJ, CANAL 0, TERMINO LA CONVERSIÓN
        MOVWF ADCON0            ;CONVERTIDOR ENCENDIDO
        BSF RCSTA, SPEN         ;HABILITA LA RECEPCIÓN DE DATOS
        BSF RCSTA, CREN         ;HABILITA EL PUERTO SERIE
        BCF INTCON, T0IF        ;LIMPIA LA BANDERA DE DESBORDAMINETO
        BSF INTCON, T0IE        ;HABILITA EL DESBORDAMIENTO DEL TIMER
        BSF INTCON, GIE         ;HABILITA INTERRUPCIONES GENERALES
        CLRF PORTB              ;LIMPIA EL PUERTO B
        CLRF CONTA              ;LIMPIA EL REGISTRO DEL CONTADOR (TIMER0)
        CLRF CONTA1             ;LIMPIA EL REGISTRO DEL CONTADOR (TIMER0)

LOOPP:  BSF ADCON0, 2           ;PONE EN 1 LA BANDERA DE GO/DONE INICIA EL PROCESO DE CONVERSIÓN
        CALL RETCA              ;LLAMADA A LA SUBRUTINA RETCA

ESPCA:  BTFSC ADCON0, 2         ;VERIFICA EL ESTADO DE LA COVERSIÓN
        GOTO ESPCA              ;SI ESTÁ EN CERO SALTA UNA INSTRUCCIÓN 
        MOVF ADRESH, W          ;MUEVE EL RESULTADO DE LA CONVERSIÓN A W
        MOVWF CCPR2L            ;MUEVE EL CONTENIDO DE W A EL REGISTRO QUE CONTROLA EL TIEMPO DE ALTO DE LA SEÑAL;MOVWF PORTB             ;MUEVE EL CONTENIDO DE W AL PUERTO B
        CALL RETARDO            ;LLAMADA A SUBRUTINA RETARDO;RETURN;GOTO LOOPP              ;SALTO A RUTINA PARA VOLVER A LEER DATOS DE UNA NUEVA CONVERSIÓN

RECIBE: BTFSS PIR1, RCIF        ;REVISA EL ESTADO DE LA TRASMICIÓN
        GOTO RECIBE             ;RETORNA A LA RUTINA PARA TERMINAR LA RECEPCIÓN DE DATOS
        MOVF RCREG, W           ;MUEVE EL CONTENIDO DEL REGISTRO DE RECEPCIÓN A W
        MOVWF DATO              ;SIRVE PARA DEFINIR LAS ACCIONES DEL ROBOT
        MOVWF TXREG             ;MUEVE EL CONTENIDO DEL REGISTRO W AL REGISTRO DE TRASMICIÓN
        BSF STATUS, RP0         ;CAMBIO AL BANCO 0

TRASMITE:   BTFSS TXSTA, TRMT   ;VERIFICA EL ESTADO DEL REGISTRO DE CORRIMIENTO DE TRASMICIÓN
            GOTO TRASMITE       ;RETORNA PARA ESPERAR EL TERMINO DE LA TRANSMICIÓN DE DATOS
            BCF STATUS, RP0     ;REGRESA AL BANCO 0
            CALL CASOS          ;LLAMADA A SUBRUTINA PARA LOS DISTINTOS CASOS
            GOTO LOOPP         ;RETORNA LA FUNCIÓN DE RECEPCIÓN DE DATOS

CASOS:  MOVLW A'0'              ;CASO PARA DETENER EL MOVIMIENTO DEL ROBOT
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL ALTO               ;CASO PARA DETENER EL MOVIMIENTO
        MOVLW A'1'              ;CASO PARA AVANZAR HACIA ADELANTE
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL AVANZA             ;CASO PARA AVANZAR HACIA ADELANTE
        MOVLW A'2'              ;CASO PARA AVAZAR HACIA ATRÁS
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL ATRAS              ;CASO PARA IR HACIA ATRÁS
        MOVLW A'3'              ;CASO PARA IR A LA DERECHA Y ADELANTE
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL DERECHA            ;CASO PARA IR HACIA LA DERECHA Y ADELANTE
        MOVLW A'4'              ;CASO PARA IR A LA DERECHA Y ATRÁS
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL DERECHA1           ;CASO PARA IR HACIA LA DERECHA Y ATRÁS
        MOVLW A'5'              ;CASO PARA IR HACIA LA IZQUIERDA Y ADELANTE
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL IZQUIERDA          ;CASO PARA IR A LA IZQUIERDA Y ADELANTE
        MOVLW A'6'              ;CASO PARA IR HACIA LA IZQUIERDA Y ATRÁS
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL IZQUIERDA1         ;CASO PARA IR A LA IZQUIERDA Y ATRÁS
        MOVLW A'7'              ;CASO PARA HACER UN TROMPO A LA DERECHA
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL TROMPOD            ;CASO PARA IR A LA RUTINA DE TROMPO
        MOVLW A'8'              ;CASO PARA HACER TROMPO A LA IZQUIERDA
        SUBWF DATO, 0           ;SE RESTA EL CONTENIDO DE W A DATO
        BTFSC STATUS, Z         ;VERIFICA EL ESTADO DE LA OPERACIÓN
        CALL TROMPOI            ;CASO PARA HACER TROMPO A LA IZQUIERDA
        RETURN

ALTO:   MOVLW B'00000000'       ;VALORES PARA LA ACCIÓN DE DETERNESE
        MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
        RETURN                  ;RETORNA DE LA SUBRUTINA

AVANZA: MOVLW B'00110101'       ;VALORES PARA LA ACCIÓN DE AVANZAR
        MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
        RETURN                  ;RETORNA DE LA SUBRUTINA

ATRAS:  MOVLW B'00101110'       ;VALORES PARA LA ACCIÓN DE IR HACIA ATRÁS
        MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
        RETURN                  ;RETORNA DE LA SUBRUTINA

DERECHA:    MOVLW B'00110111'       ;VALORES PARA LA ACCIÓN DE IR A LA DERECHA Y ADELANTE
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

DERECHA1:   MOVLW B'00000110'       ;VALORES PARA LA ACCIÓN DE IR A LA DERECHA Y ATRÁS
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

IZQUIERDA:  MOVLW B'00111101'       ;VALORES PARA LA ACCIÓN DE IR A LA IZQUIERDA Y ADELANTE
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

IZQUIERDA1: MOVLW B'00101000'       ;VALORES PARA LA ACCIÓN DE IR A LA IZQUIERDA Y ATRÁS
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

TROMPOD:    MOVLW B'00110110'       ;VALORES PARA LA ACCIÓN DE HACER UN TROMPO A LA DERECHA
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

TROMPOI:    MOVLW B'00101101'       ;VALORES PARA LA ACCIÓN DE HACER UN TROMPO A LA IZQUIERDA
            MOVWF PORTB             ;CARGA EL VALOR DE LA ACCIÓN AL PUERTO B
            RETURN                  ;RETORNA DE LA SUBRUTINA

INTERRUPCIONES: BTFSS INTCON, T0IF      ;VERIFICA LA BANDERA DE DESBORDAMIENTO DEL TIMER0
                GOTO SAL_NO_FUE_TMR0    ;SALTO A RUTINA SI LA INTERRUPCIÓN NO FUE DEL TIMER 0
                INCF CONTA              ;INCREMENTA EL CONTADOR
                MOVLW D'36'              ;VALOR CONSTANTE PARA HACER QUE TIEMPO SEA DE 2 MINUTOS
                SUBWF CONTA, W          ;SE RESTA EL CONTENIDO DE W AL REGISTRO CONTA
                BTFSS STATUS, Z         ;VERIFICA EL RESULTADO DE LA OPERACIÓN
                GOTO SAL_INT            ;SALTO A LA RUTINA DE INTERRUCPCIÓN
                CLRF CONTA              ;LIMPIA LA BANDERA DE DESBORDAMIENTO
                INCF CONTA1             ;INCREMENTA EL CONTADOR 2
                MOVLW D'255'            ;VALOR CONSTANTE PARA HACER QUE TIEMPO SEA DE 2 MINUTOS
                SUBWF CONTA1, W         ;SE RESTA EL CONTENIDO DE W AL REGISTRO CONTA
                BTFSS STATUS, Z         ;VERIFICA EL RESULTADO DE LA OPERACIÓN
                GOTO SAL_INT            ;SALTO A LA RUTINA DE INTERRUCPCIÓN
                CALL MENSAJE            ;LLAMADA A RUTINA QUE IMPIME EL MENSAJE
                CALL ALTO
                CLRF CONTA1             ;LIMPIA LA BANDERA DE DESBORDAMIENTO
                GOTO $                  ;CICLO INFINITO PARA QUE NO SALGA DE ESTE BUCLE

SAL_INT:    BCF INTCON, T0IF    ;PONE EN CERO LA BANDERA DE DESBORDAMIENTO

SAL_NO_FUE_TMR0:    RETFIE      ;RETORNA DE LA INTERRUPCIÓN

MENSAJET0:  MOVWF TXREG         ;MUEVE EL CONTENIDO DEL REGISTRO W AL REGISTRO DE TRASMICIÓN
            BSF STATUS, RP0     ;CAMBIO AL BANCO 0
            BTFSS TXSTA, TRMT   ;VERIFICA EL ESTADO DEL REGISTRO DE CORRIMIENTO DE TRASMICIÓN
            GOTO $-1            ;CICLO QUE SE REPITE HASTA QUE TERMINE LA TRASMICIÓN DE DATOS
            BCF STATUS, RP0     ;CAMBIO A BANCO 0
            RETURN              ;RETORNA DE LA SUBRUTINA

RETARDO:MOVLW CTE1              ;GUARDA EN W EL VALOR DE CTE1 = 80H
        MOVWF VALOR1            ;MUEVE EL CONTENIDO DE W AL REGISTRO VALOR1

TRES:   MOVLW CTE2              ;GUARDA EN W EL VALOR DE CTE2 = 50H
        MOVWF VALOR2            ;MUEVE EL CONTENIDO DE W AL REGISTRO VALOR1

DOS:    MOVLW CTE3              ;GUARDA EN W EL VALOR DE CTE2 = 50H
        MOVWF VALOR3            ;MUEVE EL CONTENIDO DE W AL REGISTRO VALOR1

UNO:    DECFSZ VALOR3           ;DECREMENTA UNA UNIDAD AL REGISTRO VALOR Y SI EL RESULTADO ES CERO SALTA UNA LÍNEA
        GOTO UNO                ;RETORNA AL INICIO DE LA RUTINA
        DECFSZ VALOR2           ;DECREMENTA UNA UNIDAD AL REGISTRO VALOR Y SI EL RESULTADO ES CERO SALTA UNA LÍNEA
        GOTO DOS                ;RETORNA A LA RUTINA DOS
        DECFSZ VALOR1           ;DECREMENTA UNA UNIDAD AL REGISTRO VALOR Y SI EL RESULTADO ES CERO SALTA UNA LÍNEA
        GOTO TRES               ;RETORNA A LA RUTINA TRES
        RETURN                  ;RETORNA DE LA LLAMADA

RETCA:  MOVLW 30H              ;SE CARGA EL REGISTRO W CON EL VALOR 0X30
        MOVWF 0X30              ;MUEVE EL CONTENIDO DEL REGISTRO W AL REGISTRO 0X30

ESP_CA: DECFSZ 0X30             ;DECREMENTA UNA UNIDAD AL REGISTRO 0X30 Y SI EL RESULTADO ES CERO SALTA UNA LÍNEA
        GOTO ESP_CA             ;RETORNA AL INICIO DE LA RUTINA
        RETURN                  ;RETORNA DEL LLAMADO

MENSAJE:    MOVLW A'T'          ;MENSAJE A DESPLEGAR A LA HORA DE LA INTERRUPCIÓN
            CALL MENSAJET0
            MOVLW A'I'
            CALL MENSAJET0
            MOVLW A'E'
            CALL MENSAJET0
            MOVLW A'M'
            CALL MENSAJET0
            MOVLW A'P'
            CALL MENSAJET0
            MOVLW A'O'
            CALL MENSAJET0
            MOVLW A' '
            CALL MENSAJET0
            MOVLW A'A'
            CALL MENSAJET0
            MOVLW A'G'
            CALL MENSAJET0
            MOVLW A'O'
            CALL MENSAJET0
            MOVLW A'T'
            CALL MENSAJET0
            MOVLW A'A'
            CALL MENSAJET0
            MOVLW A'D'
            CALL MENSAJET0
            MOVLW A'O'
            CALL MENSAJET0
            RETURN
            END