		PROCESSOR 16F877
  		INCLUDE<P16F877.INC>

VAL EQU H'20'	;VARIABLES PARA EL DELAY
CAL1 EQU H'21'	;CANALES
CAL2 EQU H'22'
CAL3 EQU H'23'

  		ORG 0H
  		GOTO INICIO
  
		ORG 05H
INICIO:	CLRF PORTA
       	CLRF PORTB
       	BSF STATUS,RP0    ;CAMBIA LA BANCO 1
       	BCF STATUS,RP1 
       	MOVLW 00H         ;CONFIGURA PUERTOS A Y E COMO ANALÓGICOS
       	MOVWF ADCON1
       	MOVLW 3FH         ;CONFIGURA EL PURTO A COMO ENTRADA
       	MOVWF TRISA
       	MOVLW H'0'
       	MOVWF TRISB       ;CONFIGURA PUERTO B COMO SALIDA
       	BCF STATUS,RP0    ;REGRESA AL BANCO 0

CICLO:  MOVLW B'11000001' ;CONFIGURACIÓN ADCON0 CANAL 0
       	MOVWF ADCON0
       	BSF ADCON0,2      ;CONVERSION EN PROGRESO GO=1
       	CALL RETARDO      ;ESPERA QUE TERMINE LA CONVERSIÓN

ESPERA1:	BTFSC ADCON0,2    ;PREGUNTA POR DONE(TERMINO CONVERSIÓN?)
       		GOTO ESPERA1
       		MOVF ADRESH,0     ;MUEVE A W
       		MOVWF CAL1        ;GUARDAMOS EL VALOR EN CAL1
       		MOVLW B'11001001' ;CONFIGURACIÓN ADCON0 CANAL 1
       		MOVWF ADCON0
       		BSF ADCON0,2      ;CONVERSIÓN EN PROGRESO GO=1
       		CALL RETARDO      ;ESPERA QUE TERMINE LA CONVERSIÓN

ESPERA2:    BTFSC ADCON0,2    ;PREGUNTA POR DONE(TERMINO CONVERSIÓN?)
       	    GOTO ESPERA1
       	    MOVF ADRESH,0     ;MUEVE A W
       	    MOVWF CAL2        ;GUARDAMOS EL VALOR EN CAL2
            MOVLW B'11010001' ;CONFIGURACIÓN ADCON0 CANAL 1
            MOVWF ADCON0
       		BSF ADCON0,2      ;CONVERSIÓN EN PROGRESO GO=1
       		CALL RETARDO      ;ESPERA QUE TERMINE LA CONVERSIÓN

ESPERA3:    BTFSC ADCON0,2    ;PREGUNTA POR DONE(TERMINO CONVERSIÓN?)
       	    GOTO ESPERA3
       	    MOVF ADRESH,0     ;MUEVE A W
       	    MOVWF CAL3        ;GUARDAMOS EL VALOR EN CAL3
            MOVF CAL1, W      ;MUEVE CAL1 A W
            SUBWF CAL2,W      ;RESTA CAL 2 - CAL1
            BTFSS STATUS, C   ;VERIFICA SI W ES MAYOR
            GOTO CAL1CAL2     ;SI CAL1 > CAL2
            GOTO CAL2CAL1     ;SI CAL2 < CAL1

CAL1CAL2:   MOVF CAL1, W
            SUBWF CAL3, W
            BTFSS STATUS, C
            GOTO SALIDA1
            GOTO SALIDA3

CAL2CAL1:   MOVF CAL2, W
            SUBWF CAL3, W
            BTFSS STATUS, C
            GOTO SALIDA2
            GOTO SALIDA3

SALIDA1:	MOVLW H'1'        
       		MOVWF PORTB     ;SALIDA 0001
       		GOTO CICLO

SALIDA2:	MOVLW H'2'      ;SALIDA 0010
       		MOVWF PORTB
       		GOTO CICLO

SALIDA3:	MOVLW H'3'      ;SALIDA 0011
       		MOVWF PORTB
       		GOTO CICLO

RETARDO:	MOVLW H'30'		;DELAY DE 2MICOSEG APROX.
			MOVWF VAL

LOOP:	DECFSZ VAL
      	GOTO LOOP
      	RETURN
   		END
