		PROCESSOR 16F877
  		INCLUDE<P16F877.INC>

VAL EQU H'20'	;VARIABLE PARA EL DELAY
		
		ORG 0H
  		GOTO INICIO
  		
		ORG 05H
INICIO:	CLRF PORTA        ;LIMPIA EL PUERTO A
      	CLRF PORTB        ;LIMPIA EL PUERTO B
      	BSF STATUS,RP0    
      	BCF STATUS,RP1    ;CAMBIO LA BANCO 1
      	MOVLW 00H         
      	MOVWF ADCON1      ;CONFIGURA PUERTO A Y E COMO ANALÓGICOS
      	MOVLW 3FH         
      	MOVWF TRISA       ;CONFIGURA EL PUERTO A COMO ENTRADA
      	MOVLW H'0'
      	MOVWF TRISB       ;CONFIGURA PUERTO B COMO SALIDA
      	BCF STATUS,RP0    ;REGRESA AL BANCO 0
      	MOVLW B'11000001' ;CONFIGURACIÓN ADCON0 
      	MOVWF ADCON0      ;ADCS1=1 ADCS0=1 CHS2=0 CHS1=0 CHS0=0
						  ; GO/DONE=0 - ADON=1
CICLO: 	BSF ADCON0,2     ;CONVERSIÓN EN PROGRESO GO=1
       	CALL RETARDO     ;ESPERA QUE TERMINE LA CONVERSIÓN

ESPERA: BTFSC ADCON0,2   ;PREGUNTA POR DONE=0?(TERMINÓ CONVERSIÓN?)
       	GOTO ESPERA      ;NO, VUELVE A PREGUNTAR
       	MOVF ADRESH,0    ;SI
       	MOVWF PORTB      ;MUESTRA EL RESULTADO EN PORTB
       	GOTO CICLO

RETARDO:	MOVLW H'30'	 ;DELAY DE 20 MICROSEG APROX. 
       		MOVWF VAL

LOOP:	DECFSZ VAL
       	GOTO LOOP
       	RETURN
    	END
